version: '3.7'
services:
  web:
    build: nginx
    ports:
      - 80:80
      - 443:443
    depends_on:
      - api
  api:
    image: eyd_api
    env_file:
      - api.env
    ports: 
      - "8080:8080"
    environment:
      - PORT=8080
    volumes:
      - /Users/silvio/Documents/EnrichYourData/api/app:/app
  
    