version: '3.8'

services:
  api:
    container_name: eyd_api
    build:
       context: ./services/api
    command: uvicorn main:app --reload --host 0.0.0.0 --port 5000
    env_file:
      - api.env
    expose:
      - 5000
    labels:
      - "traefik.enable=true"
      ## USE THIS TO WORK ONLY IN LOCAL
      ## - "traefik.http.routers.fastapi.rule=Host(`fastapi.localhost`)" 
      ## USE THIS TO WORK REMOTELY
      - "traefik.http.routers.fastapi.rule=Host(`134.122.102.92`)"
    volumes:
      - "./services/api/app:/home/app/api"
  traefik:
    image: traefik
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./services/traefik/traefik.dev.toml:/etc/traefik/traefik.toml"
      - "./services/traefik/log:/var/log"
  database:
    image: mongo
    container_name: eyd_db
    env_file:
      - db.env
    ports:
      - "27030:27017"
    volumes:
      - "./services/db/initdb.d/:/docker-entrypoint-initdb.d"
      - "./services/db/mongo-volume:/data/db"
      - "./services/db/log:/var/log/mongodb"

