version: '3.8'

services:
  api:
    container_name: eyd_api
    depends_on:
      - database
      - traefik
    build:
       context: ./services/api
    env_file:
      - api.env
    command: uvicorn main:app --host 0.0.0.0 --port 5000
    expose:
      - 5000
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.fastapi.rule=Host(`disinformationpolimi.me`)"
      - "traefik.http.routers.fastapi.tls=true"
      - "traefik.http.routers.fastapi.tls.certresolver=letsencrypt"
    volumes:
      - "./services/api/app:/home/app/api"
  traefik:
    container_name: traefik
    image: traefik:latest
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./services/traefik/traefik.prod.toml:/etc/traefik/traefik.toml"
      - "./services/traefik/acme.json:/acme.json"
  database:
    image: mongo
    container_name: eyd_db
    restart: always
    env_file:
      - db.env
    ports:
      - "27030:27017"
    volumes:
      - "./services/db/initdb.d/:/docker-entrypoint-initdb.d"
      - "./services/db/mongo-volume:/data/db"
      - "./services/db/log:/var/log/mongodb"