version: '3.8'

services:
  api:
    container_name: eyd_api
    depends_on:
      - database
      - traefik
    build:
       context: ./services/api
    env_file:
      - api.prod.env
    command: uvicorn main:app --host 0.0.0.0 --port 5000
    expose:
      - 5000
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.fastapi.rule=Host(`disinformationpolimi.me`)"
      - "traefik.http.routers.fastapi.tls=true"
      - "traefik.http.routers.fastapi.tls.certresolver=letsencrypt"
    volumes:
      - "./services/api/app:/home/app/api"
    networks:
      - web
  traefik:
    container_name: traefik
    image: traefik:latest
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./services/traefik/traefik.prod.toml:/etc/traefik/traefik.toml"
      - "./services/traefik/acme.json:/acme.json"
    networks:
      - web
  database:
    image: mongo
    container_name: eyd_db
    restart: always
    env_file:
      - db.env
    ports:
      - "27030:27017"
    volumes:
      - "./services/db/initdb.d/:/docker-entrypoint-initdb.d"
      - "./services/db/mongo-volume:/data/db"
      - "./services/db/log:/var/log/mongodb"
    networks:
      - web
  static:  # nginx to serve static files
    image: nginx:alpine
    container_name: static-files
    restart: always
    volumes:
      - "./services/nginx/default.conf:/etc/nginx/conf.d/default.conf"
      - "./services/api/app/static:/static"
    labels:  # route defined to handle specific rule and enabling tls certresolver
      # - "traefik.enable=true"
      # - "traefik.http.routers.static-files.entrypoints=websecure"
      # - "traefik.http.routers.static-files.rule=Host(`disinformationpolimi.me`) && PathPrefix(`/static`)" 
      - "traefik.enable=true"
      - "traefik.backend=nginx"
      - "traefik.frontend.rule=Host:disinformationpolimi.me;PathPrefix:/static"
      - "traefik.port=443"
      - "traefik.http.routers.static-files.tls.certresolver=letsencrypt" 
    networks:
      - web
    depends_on:
      - api
networks:
   web:
      external: true