[entryPoints]
  [entryPoints.web]
    address = ":80"

[api]
insecure = true

[log]
level = "DEBUG"

[accessLog]
  filePath = "/var/log/access.log"

[providers]
  [providers.docker]
    exposedByDefault = false