# [entryPoints]
#   [entryPoints.web]
#     address = ":80"
#   [entryPoints.web.http]
#     [entryPoints.web.http.redirections]
#       [entryPoints.web.http.redirections.entryPoint]
#         to = "websecure"
#         scheme = "https"

#   [entryPoints.websecure]
#     address = ":443"

# [accessLog]
#   filePath = "/var/log/access.log"

# [providers]
#   [providers.docker]
#     exposedByDefault = false

# [certificatesResolvers.letsencrypt.acme]
#   email = "silvio.pavanetto@polimi.it"
#   storage= "acme.json"
#   [certificatesResolvers.letsencrypt.acme.httpChallenge]
#     entryPoint = "web"

debug = false

logLevel = "ERROR"
defaultEntryPoints = ["https","http"]

[accessLog]
  filePath = "/var/log/access.log"

[entryPoints]
  [entryPoints.http]
  address = ":80"
    [entryPoints.http.redirect]
    entryPoint = "https"
  [entryPoints.https]
  address = ":443"
  [entryPoints.https.tls]

[retry]

[docker]
endpoint = "unix:///var/run/docker.sock"
domain = "disinformationpolimi.me"
watch = true
exposedByDefault = false

[acme]
email = "polimi@disinformationpolimi.me"
storage = "acme.json"
entryPoint = "https"
onHostRule = true
[acme.httpChallenge]
entryPoint = "http"